### ISSUE TITLE
关于cache的一些疑问

### ISSUE THREAD

**Issue by shiniao** [1024casts/snake#3]
（新手轻拍）
看了您的代码，pkg/cache封装了memory和redis，对外提供driver，然后在internal的cache包中针对不同业务使用cache，那么我看到internal/service/vcode中，要把验证码存放到缓存中，直接调用了pkg/redis中的client，为什么不通过封装好的cache接口来调用

**Comment by qloog** [comment]
@shiniao 好问题，主要有两个原因：
1、vcode的实现是在增加cache之前做的
2、验证码相对独立，比较算公共模块，和业务逻辑耦合不大
基于以上，所以就没有按照封装独立cache的方式来做

如果独立cache来做也是没有问题的。

**Comment by shiniao** [comment]
@qloog 懂了，看了这个项目的代码，学到了很多，尤其是整个分层的设计，收益匪浅，谢谢！

**Comment by qloog** [comment]
@shiniao 很高兴能够对你有所帮助~
