### ISSUE TITLE
关于service层的疑惑

### ISSUE THREAD

**Issue by FirYuen** [1024casts/snake#34]
目前的结构在service层写了所有的方法,每次调用时会比较难找到自己想要的方法
比如 目前的架构中 定义了
var (
	UserSvc  *Service
	VCodeSvc *Service
)
但是在handler中调用service.UserSvc时,ide也会提示VCodeSvc下的相关方法,有优化的方式吗

**Comment by qloog** [comment]
可以把 service 按职责分开，比如用户一个service,  订单一个service, 分别有自己的New方法(NewUserService, NewOrderService)，目前是一个大service, 一个New，所有的都在一个下面，就会有你说的这种问题。
