### ISSUE TITLE
无法正常启动服务，并且程序不能按配置使用8080端口

### ISSUE THREAD

**Issue by uzi-2016** [1024casts/snake#8]
你好，我按照readme的提示通过clone的方式安装了整个框架，并且复制了一份本地配置conf/config.local.yaml，修改了数据库的密码和日志存放位置，本地redis是默认的，安装好依赖之后，程序已经能正常启动，但是不能进行web访问。另外，配置设置的是8080端口，但似乎程序使用的是1234端口，具体见下方的截图：
<img width="1045" alt="WechatIMG295" src="https://user-images.githubusercontent.com/19517597/94296759-f0008f80-ff95-11ea-9ef9-1d96d44239cb.png">程序运行截图
<img width="792" alt="WechatIMG296" src="https://user-images.githubusercontent.com/19517597/94296788-fee74200-ff95-11ea-8f0e-c4f4ccb9ceab.png">8080截图
<img width="872" alt="WechatIMG297" src="https://user-images.githubusercontent.com/19517597/94296825-0c9cc780-ff96-11ea-8d3b-594350574d7e.png">1234截图
<img width="592" alt="WechatIMG299" src="https://user-images.githubusercontent.com/19517597/94296843-158d9900-ff96-11ea-9d3f-a67016f47246.png">配置截图

(个人认为操作上应该没有什么问题，不过也可能存在姿势不对的情况，跪求大佬指点)
go version go1.14.6 darwin/amd64

**Comment by qloog** [comment]
@uzi-2016  已修复，是因为开启了 grpc server 阻塞了， 导致 api server 没有启动。已改为通过 goroutine启动 grpc server。

**Comment by uzi-2016** [comment]
感谢大佬的修复，api服务已经正常启动，问题已验证，我会好好体验下snake框架。
（回复很及时，手动点赞，这才是开源人应有的态度，祝愿snake越来越好）

**Comment by uzi-2016** [comment]
以解决
